/** Declaration file generated by dts-gen */
import React from 'react';
import { ColorInputWithoutInstance } from 'tinycolor2';

export interface IComponentProps {
  primaryColor?: ColorInputWithoutInstance;
  storageName?: string;
  style?: CSSStyleDeclaration;
  placement?: 'bottomRight' | 'bottom' | 'bottomLeft' | 'left' | 'topLeft' | 'top' | 'topRight' | 'right',
  themeChangeCallback?: (color: ColorInputWithoutInstance) => void
}

export function changeAntdTheme(color: ColorInputWithoutInstance, customCss?: string): void;

declare class DynamicAntdTheme extends React.Component<IComponentProps> {
  static defaultProps: IComponentProps;
  constructor(props: IComponentProps);
}

export default DynamicAntdTheme;

